// Copyright (c) 2019-2021 ReactiveUI Association Incorporated. All rights reserved.
// ReactiveUI Association Incorporated licenses this file to you under the MIT license.
// See the LICENSE file in the project root for full license information.

using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Reflection;
using System.Text;

using Microsoft.CodeAnalysis;

namespace ReactiveMarbles.PropertyChanged.SourceGenerator
{
    internal static class StringBuilderSourceCreatorHelper
    {
        private static readonly string AutoGeneratedString = @"// <auto-generated>
// This code is auto generated do not modify.
// <auto-generated />";

        public static string GetAutoGeneratedString() => AutoGeneratedString;

        public static string GetMultiExpressionMethodParameters(string inputType, string outputType, List<string> tempReturnTypes)
        {
            var sb = new StringBuilder();
            var counter = tempReturnTypes.Count;

            for (int i = 0; i < counter; i++)
            {
                sb.Append("        Func<").Append(inputType).Append(", ").Append(tempReturnTypes[i]).Append("> propertyExpression").Append(i + 1).AppendLine(",");
            }

            sb.Append("        Func<");
            for (int i = 0; i < counter; i++)
            {
                sb.Append(tempReturnTypes[i]).Append(", ");
            }

            sb.Append(outputType).Append("> conversionFunc)");

            return sb.ToString();
        }

        public static string GetMultiExpressionMethodBody(int counter)
        {
            var sb = new StringBuilder();
            for (int i = 0; i < counter; i++)
            {
                sb.Append("        var obs").Append(i + 1).Append(" = objectToMonitor.WhenChanged(propertyExpression").Append(i + 1).AppendLine(");");
            }

            sb.Append("        return obs1.CombineLatest(");
            for (int i = 1; i < counter; i++)
            {
                sb.Append("obs").Append(i + 1).Append(", ");
            }

            sb.Append("conversionFunc);");

            return sb.ToString();
        }

        public static string GetMultiExpressionMethodBodyForPartialClass(int counter)
        {
            var sb = new StringBuilder();
            for (int i = 0; i < counter; i++)
            {
                sb.Append("        var obs").Append(i + 1).Append(" = this.WhenChanged(propertyExpression").Append(i + 1).AppendLine(");");
            }

            sb.Append("        return obs1.CombineLatest(");
            for (int i = 1; i < counter; i++)
            {
                sb.Append("obs").Append(i + 1).Append(", ");
            }

            sb.Append("conversionFunc);");

            return sb.ToString();
        }

        public static string GetMultiExpressionMethod(string inputType, string outputType, Accessibility accessModifier, string expressionParameters, string body)
        {
            return $@"
    {accessModifier.ToFriendlyString()} static IObservable<{outputType}> WhenChanged(
        this {inputType} objectToMonitor,
{expressionParameters}
    {{
{body}
    }}
";
        }

        public static string GetMultiExpressionMethodForPartialClass(string inputType, string outputType, Accessibility accessModifier, string expressionParameters, string body)
        {
            return $@"
    {accessModifier.ToFriendlyString()} IObservable<{outputType}> WhenChanged(
{expressionParameters}
    {{
{body}
    }}
";
        }

        public static string GetWhenChangedMethodForMap(string inputType, string outputType, Accessibility accessModifier, string mapName)
        {
            return $@"
    {accessModifier.ToFriendlyString()} static IObservable<{outputType}> WhenChanged(this {inputType} source, Expression<Func<{inputType}, {outputType}>> propertyExpression)
    {{
        return {mapName}[propertyExpression.Body.ToString()].Invoke(source);
    }}
";
        }

        public static string GetObservableCreation(string inputType, string inputName, string outputType, string memberName)
        {
            return $@"Observable.Create<{outputType}>(
                observer =>
                {{
                    PropertyChangedEventHandler handler = (object sender, PropertyChangedEventArgs e) =>
                    {{
                        var input = ({inputType}){inputName};
                        if (e.PropertyName == ""{memberName}"")
                        {{
                            observer.OnNext(input.{memberName});
                        }}
                    }};

                    {inputName}.PropertyChanged += handler;

                    return Disposable.Create((parent: {inputName}, handler), x => x.parent.PropertyChanged -= x.handler);
                }})
            .StartWith({inputName}.{memberName})";
        }

        public static string GetWhenChangedMethodForDirectReturn(string inputType, string outputType, Accessibility accessModifier, string valueChain)
        {
            return $@"
    /// <summary>
    /// Generates a IObservable which signals with updated property value changes.
    /// </summary>
    /// <param name=""source"">The source of the property changes.</param>
    /// <param name=""propertyExpression"">The property.</param>
    /// <returns>The observable which signals with updates.</returns>
    {accessModifier.ToFriendlyString()} static IObservable<{outputType}> WhenChanged(this {inputType} source, Expression<Func<{inputType}, {outputType}>> propertyExpression)
    {{
        return Observable.Return(source){valueChain};
    }}
";
        }

        public static string GetMapEntryChain(string inputType, string outputType, string memberName)
        {
            return $@"
                .Where(x => x != null)
                .Select(x => {GetObservableCreation(inputType, "x", outputType, memberName)})
                .Switch()";
        }

        public static string GetMapEntry(string key, string valueChain)
        {
            return $@"
        {{
            ""{key}"",
            source => Observable.Return(source){valueChain}
        }},";
        }

        public static string GetMap(string inputType, string outputType, string mapName, string entries)
        {
            return $@"
    private static readonly Dictionary<string, Func<{inputType}, IObservable<{outputType}>>> {mapName} = new Dictionary<string, Func<{inputType}, IObservable<{outputType}>>>()
    {{
{entries}
    }};
";
        }

        public static string GetClass(string body)
        {
            return $@"
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq.Expressions;
using System.Reactive.Disposables;
using System.Reactive.Linq;

public static partial class NotifyPropertyChangedExtensions
{{
    {body}
}}
";
        }

        public static string GetPartialClass(string namespaceName, string className, Accessibility accessModifier, IEnumerable<AncestorClassInfo> ancestorClasses, string body)
        {
            var source = $@"
{accessModifier.ToFriendlyString()} partial class {className}
{{
    {body}
}}
";

            foreach (var ancestorClass in ancestorClasses)
            {
                source = $@"
{ancestorClass.AccessModifier.ToFriendlyString()} partial class {ancestorClass.Name}
{{
{source}
}}
";
            }

            if (!string.IsNullOrEmpty(namespaceName))
            {
                source = $@"
namespace {namespaceName}
{{
{source}
}}
";
            }

            var usingClauses = @"
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq.Expressions;
using System.Reactive.Disposables;
using System.Reactive.Linq;
";

            return source.Insert(0, usingClauses);
        }

        public static string GetPartialClassWhenChangedMethodForMap(string inputType, string outputType, Accessibility accessModifier, string mapName)
        {
            return $@"
    {accessModifier.ToFriendlyString()} IObservable<{outputType}> WhenChanged(Expression<Func<{inputType}, {outputType}>> propertyExpression)
    {{
        return {mapName}[propertyExpression.Body.ToString()].Invoke(this);
    }}
";
        }

        public static string GetPartialClassWhenChangedMethodForDirectReturn(string inputType, string outputType, Accessibility accessModifier, string valueChain)
        {
            // Making the access modifier public so multi-expression extensions will able to access it, if needed.
            return $@"
    {accessModifier.ToFriendlyString()} IObservable<{outputType}> WhenChanged(Expression<Func<{inputType}, {outputType}>> propertyExpression)
    {{
        return {GetObservableCreation(inputType, "x", outputType, valueChain)};
    }}
";
        }

        public static string GetWhenChangedStubClass()
        {
            var assembly = Assembly.GetExecutingAssembly();
            const string resourceName = "ReactiveMarbles.PropertyChanged.SourceGenerator.NotifyPropertyChangedExtensions.cs";

            using Stream stream = assembly.GetManifestResourceStream(resourceName);
            using StreamReader reader = new StreamReader(stream);
            return reader.ReadToEnd();
        }

        public static string GetBindingStubClass()
        {
            var assembly = Assembly.GetExecutingAssembly();
            const string resourceName = "ReactiveMarbles.PropertyChanged.SourceGenerator.BindExtensions.cs";

            using Stream stream = assembly.GetManifestResourceStream(resourceName);
            using StreamReader reader = new StreamReader(stream);
            return reader.ReadToEnd();
        }
    }
}
