// Copyright (c) 2019-2021 ReactiveUI Association Incorporated. All rights reserved.
// ReactiveUI Association Incorporated licenses this file to you under the MIT license.
// See the LICENSE file in the project root for full license information.
// <auto-generated />

namespace ReactiveMarbles.PropertyChanged.SourceGenerator
{
    internal static partial class Constants
    {
        internal const string WhenChangedMethodName = "WhenChanged";

        internal const string WhenChangingMethodName = "WhenChanging";

        internal const string BindMethodName = "BindTwoWay";

        internal const string OneWayBindMethodName = "BindOneWay";

        internal const string WhenChangedExtensionClass = "NotifyPropertyChangedExtensions";
    }
}
